-- Local-only QA seed for AliPicks.
-- This file is executed by `supabase db reset` in local development.
--
-- IMPORTANT:
-- Do not manually INSERT a login-capable user into auth.users here. Supabase Auth
-- maintains additional invariants/identity records and the Auth server may return
-- HTTP 500 when a hand-crafted auth.users row is incomplete. Create the local QA
-- admin through the Auth Admin API instead (see scripts/create-local-admin.ts).
--
-- Keep the local QA dataset intentionally small. Ligas, equipos and picks should
-- be created through the actual Admin UI during functional testing so React Query,
-- validation and the domain RPCs are exercised end-to-end.
