/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as PagoRouteImport } from './routes/pago'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as PicksIndexRouteImport } from './routes/picks.index'
import { Route as PicksIdRouteImport } from './routes/picks.$id'
import { Route as AuthenticatedAdminLeaguesRouteImport } from './routes/_authenticated/admin.leagues'
import { Route as AuthenticatedAdminTeamsRouteImport } from './routes/_authenticated/admin.teams'
import { Route as AuthenticatedAdminPicksIdRouteImport } from './routes/_authenticated/admin.picks.$id'
import { Route as AuthenticatedAdminPicksNewRouteImport } from './routes/_authenticated/admin.picks.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoRoute = PagoRouteImport.update({
  id: '/pago',
  path: '/pago',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PicksIndexRoute = PicksIndexRouteImport.update({
  id: '/picks/',
  path: '/picks/',
  getParentRoute: () => rootRouteImport,
} as any)
const PicksIdRoute = PicksIdRouteImport.update({
  id: '/picks/$id',
  path: '/picks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminLeaguesRoute =
  AuthenticatedAdminLeaguesRouteImport.update({
    id: '/leagues',
    path: '/leagues',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTeamsRoute = AuthenticatedAdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPicksIdRoute =
  AuthenticatedAdminPicksIdRouteImport.update({
    id: '/picks/$id',
    path: '/picks/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPicksNewRoute =
  AuthenticatedAdminPicksNewRouteImport.update({
    id: '/picks/new',
    path: '/picks/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/historial': typeof HistorialRoute
  '/metodologia': typeof MetodologiaRoute
  '/pago': typeof PagoRoute
  '/planes': typeof PlanesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/picks/$id': typeof PicksIdRoute
  '/picks/': typeof PicksIndexRoute
  '/admin/leagues': typeof AuthenticatedAdminLeaguesRoute
  '/admin/teams': typeof AuthenticatedAdminTeamsRoute
  '/admin/picks/$id': typeof AuthenticatedAdminPicksIdRoute
  '/admin/picks/new': typeof AuthenticatedAdminPicksNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/historial': typeof HistorialRoute
  '/metodologia': typeof MetodologiaRoute
  '/pago': typeof PagoRoute
  '/planes': typeof PlanesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/picks/$id': typeof PicksIdRoute
  '/picks': typeof PicksIndexRoute
  '/admin/leagues': typeof AuthenticatedAdminLeaguesRoute
  '/admin/teams': typeof AuthenticatedAdminTeamsRoute
  '/admin/picks/$id': typeof AuthenticatedAdminPicksIdRoute
  '/admin/picks/new': typeof AuthenticatedAdminPicksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/historial': typeof HistorialRoute
  '/metodologia': typeof MetodologiaRoute
  '/pago': typeof PagoRoute
  '/planes': typeof PlanesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/picks/$id': typeof PicksIdRoute
  '/picks/': typeof PicksIndexRoute
  '/_authenticated/admin/leagues': typeof AuthenticatedAdminLeaguesRoute
  '/_authenticated/admin/teams': typeof AuthenticatedAdminTeamsRoute
  '/_authenticated/admin/picks/$id': typeof AuthenticatedAdminPicksIdRoute
  '/_authenticated/admin/picks/new': typeof AuthenticatedAdminPicksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/historial'
    | '/metodologia'
    | '/pago'
    | '/planes'
    | '/admin'
    | '/perfil'
    | '/picks/$id'
    | '/picks/'
    | '/admin/leagues'
    | '/admin/teams'
    | '/admin/picks/$id'
    | '/admin/picks/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/historial'
    | '/metodologia'
    | '/pago'
    | '/planes'
    | '/admin'
    | '/perfil'
    | '/picks/$id'
    | '/picks'
    | '/admin/leagues'
    | '/admin/teams'
    | '/admin/picks/$id'
    | '/admin/picks/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/historial'
    | '/metodologia'
    | '/pago'
    | '/planes'
    | '/_authenticated/admin'
    | '/_authenticated/perfil'
    | '/picks/$id'
    | '/picks/'
    | '/_authenticated/admin/leagues'
    | '/_authenticated/admin/teams'
    | '/_authenticated/admin/picks/$id'
    | '/_authenticated/admin/picks/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HistorialRoute: typeof HistorialRoute
  MetodologiaRoute: typeof MetodologiaRoute
  PagoRoute: typeof PagoRoute
  PlanesRoute: typeof PlanesRoute
  PicksIdRoute: typeof PicksIdRoute
  PicksIndexRoute: typeof PicksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago': {
      id: '/pago'
      path: '/pago'
      fullPath: '/pago'
      preLoaderRoute: typeof PagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/picks/': {
      id: '/picks/'
      path: '/picks'
      fullPath: '/picks/'
      preLoaderRoute: typeof PicksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picks/$id': {
      id: '/picks/$id'
      path: '/picks/$id'
      fullPath: '/picks/$id'
      preLoaderRoute: typeof PicksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/leagues': {
      id: '/_authenticated/admin/leagues'
      path: '/leagues'
      fullPath: '/admin/leagues'
      preLoaderRoute: typeof AuthenticatedAdminLeaguesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/teams': {
      id: '/_authenticated/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AuthenticatedAdminTeamsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/picks/$id': {
      id: '/_authenticated/admin/picks/$id'
      path: '/picks/$id'
      fullPath: '/admin/picks/$id'
      preLoaderRoute: typeof AuthenticatedAdminPicksIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/picks/new': {
      id: '/_authenticated/admin/picks/new'
      path: '/picks/new'
      fullPath: '/admin/picks/new'
      preLoaderRoute: typeof AuthenticatedAdminPicksNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminLeaguesRoute: typeof AuthenticatedAdminLeaguesRoute
  AuthenticatedAdminTeamsRoute: typeof AuthenticatedAdminTeamsRoute
  AuthenticatedAdminPicksIdRoute: typeof AuthenticatedAdminPicksIdRoute
  AuthenticatedAdminPicksNewRoute: typeof AuthenticatedAdminPicksNewRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminLeaguesRoute: AuthenticatedAdminLeaguesRoute,
  AuthenticatedAdminTeamsRoute: AuthenticatedAdminTeamsRoute,
  AuthenticatedAdminPicksIdRoute: AuthenticatedAdminPicksIdRoute,
  AuthenticatedAdminPicksNewRoute: AuthenticatedAdminPicksNewRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HistorialRoute: HistorialRoute,
  MetodologiaRoute: MetodologiaRoute,
  PagoRoute: PagoRoute,
  PlanesRoute: PlanesRoute,
  PicksIdRoute: PicksIdRoute,
  PicksIndexRoute: PicksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
